//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace Dyvenix.GenIt
{
	/// <summary>
	/// DomainModel GenItDomainModel
	/// Description for Dyvenix.GenIt.GenIt
	/// </summary>
	[DslDesign::DisplayNameResource("Dyvenix.GenIt.GenItDomainModel.DisplayName", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Dyvenix.GenIt.GenItDomainModel.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("9d433ece-11d0-4cbc-9a3b-82824193f347")]
	public partial class GenItDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// GenItDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x9d433ece, 0x11d0, 0x4cbc, 0x9a, 0x3b, 0x82, 0x82, 0x41, 0x93, 0xf3, 0x47);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public GenItDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(NamedElement),
				typeof(ModelRoot),
				typeof(EntityModel),
				typeof(PropertyModel),
				typeof(Comment),
				typeof(Operation),
				typeof(ModelInterface),
				typeof(InterfaceOperation),
				typeof(ModelType),
				typeof(ClassModelElement),
				typeof(EnumMember),
				typeof(EnumModel),
				typeof(NavigationProperty),
				typeof(FilterPropertyModel),
				typeof(ReadMethodModel),
				typeof(UpdatePropertyModel),
				typeof(UpdateMethodModel),
				typeof(ServiceModel),
				typeof(Association),
				typeof(ClassHasProperties),
				typeof(ModelRootHasComments),
				typeof(Generalization),
				typeof(ModelRootHasTypes),
				typeof(InterfaceHasOperation),
				typeof(CommentReferencesSubjects),
				typeof(Implementation),
				typeof(EnumHasMembers),
				typeof(ClassHasNavigationProperties),
				typeof(FilterPropertyModelHasProperty),
				typeof(ReadMethodModelHasFilterProperties),
				typeof(UpdatePropertyModelHasPropertyModel),
				typeof(UpdateMethodModelHasUpdateProperties),
				typeof(ServiceModelHasReadMethodModels),
				typeof(ServiceModelHasUpdateMethods),
				typeof(EntityModelHasServiceModels),
				typeof(GenItDiagram),
				typeof(AssociationConnector),
				typeof(GeneralizationConnector),
				typeof(ImplementationConnector),
				typeof(CommentConnector),
				typeof(CommentBoxShape),
				typeof(ClassShape),
				typeof(InterfaceShape),
				typeof(EnumShape),
				typeof(global::Dyvenix.GenIt.FixUpDiagram),
				typeof(global::Dyvenix.GenIt.ConnectorRolePlayerChanged),
				typeof(global::Dyvenix.GenIt.CompartmentItemAddRule),
				typeof(global::Dyvenix.GenIt.CompartmentItemDeleteRule),
				typeof(global::Dyvenix.GenIt.CompartmentItemRolePlayerChangeRule),
				typeof(global::Dyvenix.GenIt.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::Dyvenix.GenIt.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(NamedElement), "Name", NamedElement.NameDomainPropertyId, typeof(NamedElement.NamePropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "EntitiesOutputFolder", ModelRoot.EntitiesOutputFolderDomainPropertyId, typeof(ModelRoot.EntitiesOutputFolderPropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "EntitiesNamespace", ModelRoot.EntitiesNamespaceDomainPropertyId, typeof(ModelRoot.EntitiesNamespacePropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "TemplatesFolder", ModelRoot.TemplatesFolderDomainPropertyId, typeof(ModelRoot.TemplatesFolderPropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "DbContextOutputFolder", ModelRoot.DbContextOutputFolderDomainPropertyId, typeof(ModelRoot.DbContextOutputFolderPropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "DbContextNamespace", ModelRoot.DbContextNamespaceDomainPropertyId, typeof(ModelRoot.DbContextNamespacePropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "DbContextUsings", ModelRoot.DbContextUsingsDomainPropertyId, typeof(ModelRoot.DbContextUsingsPropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "EnumsOutputFolder", ModelRoot.EnumsOutputFolderDomainPropertyId, typeof(ModelRoot.EnumsOutputFolderPropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "EnumsNamespace", ModelRoot.EnumsNamespaceDomainPropertyId, typeof(ModelRoot.EnumsNamespacePropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "EntitiesEnabled", ModelRoot.EntitiesEnabledDomainPropertyId, typeof(ModelRoot.EntitiesEnabledPropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "DbContextEnabled", ModelRoot.DbContextEnabledDomainPropertyId, typeof(ModelRoot.DbContextEnabledPropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "EnumsEnabled", ModelRoot.EnumsEnabledDomainPropertyId, typeof(ModelRoot.EnumsEnabledPropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "DiagramBackgroundColor", ModelRoot.DiagramBackgroundColorDomainPropertyId, typeof(ModelRoot.DiagramBackgroundColorPropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "AssociationLineColor", ModelRoot.AssociationLineColorDomainPropertyId, typeof(ModelRoot.AssociationLineColorPropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "InclHeader", ModelRoot.InclHeaderDomainPropertyId, typeof(ModelRoot.InclHeaderPropertyHandler)),
				new DomainMemberInfo(typeof(EntityModel), "Attributes", EntityModel.AttributesDomainPropertyId, typeof(EntityModel.AttributesPropertyHandler)),
				new DomainMemberInfo(typeof(EntityModel), "Usings", EntityModel.UsingsDomainPropertyId, typeof(EntityModel.UsingsPropertyHandler)),
				new DomainMemberInfo(typeof(EntityModel), "Auditable", EntityModel.AuditableDomainPropertyId, typeof(EntityModel.AuditablePropertyHandler)),
				new DomainMemberInfo(typeof(EntityModel), "GenerateCode", EntityModel.GenerateCodeDomainPropertyId, typeof(EntityModel.GenerateCodePropertyHandler)),
				new DomainMemberInfo(typeof(EntityModel), "InclRowVersion", EntityModel.InclRowVersionDomainPropertyId, typeof(EntityModel.InclRowVersionPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "DataType", PropertyModel.DataTypeDomainPropertyId, typeof(PropertyModel.DataTypePropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "EnumTypeName", PropertyModel.EnumTypeNameDomainPropertyId, typeof(PropertyModel.EnumTypeNamePropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "Length", PropertyModel.LengthDomainPropertyId, typeof(PropertyModel.LengthPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "InitialValue", PropertyModel.InitialValueDomainPropertyId, typeof(PropertyModel.InitialValuePropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "Attributes", PropertyModel.AttributesDomainPropertyId, typeof(PropertyModel.AttributesPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "Usings", PropertyModel.UsingsDomainPropertyId, typeof(PropertyModel.UsingsPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "IsPrimaryKey", PropertyModel.IsPrimaryKeyDomainPropertyId, typeof(PropertyModel.IsPrimaryKeyPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "IsNullable", PropertyModel.IsNullableDomainPropertyId, typeof(PropertyModel.IsNullablePropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "IsIdentity", PropertyModel.IsIdentityDomainPropertyId, typeof(PropertyModel.IsIdentityPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "IsIndexed", PropertyModel.IsIndexedDomainPropertyId, typeof(PropertyModel.IsIndexedPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "IsIndexUnique", PropertyModel.IsIndexUniqueDomainPropertyId, typeof(PropertyModel.IsIndexUniquePropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "IsIndexClustered", PropertyModel.IsIndexClusteredDomainPropertyId, typeof(PropertyModel.IsIndexClusteredPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "IsForeignKey", PropertyModel.IsForeignKeyDomainPropertyId, typeof(PropertyModel.IsForeignKeyPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyModel), "IsRowVersion", PropertyModel.IsRowVersionDomainPropertyId, typeof(PropertyModel.IsRowVersionPropertyHandler)),
				new DomainMemberInfo(typeof(Comment), "Text", Comment.TextDomainPropertyId, typeof(Comment.TextPropertyHandler)),
				new DomainMemberInfo(typeof(Operation), "Signature", Operation.SignatureDomainPropertyId, typeof(Operation.SignaturePropertyHandler)),
				new DomainMemberInfo(typeof(Operation), "Concurrency", Operation.ConcurrencyDomainPropertyId, typeof(Operation.ConcurrencyPropertyHandler)),
				new DomainMemberInfo(typeof(Operation), "Precondition", Operation.PreconditionDomainPropertyId, typeof(Operation.PreconditionPropertyHandler)),
				new DomainMemberInfo(typeof(Operation), "Postcondition", Operation.PostconditionDomainPropertyId, typeof(Operation.PostconditionPropertyHandler)),
				new DomainMemberInfo(typeof(ClassModelElement), "Description", ClassModelElement.DescriptionDomainPropertyId, typeof(ClassModelElement.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(EnumMember), "Value", EnumMember.ValueDomainPropertyId, typeof(EnumMember.ValuePropertyHandler)),
				new DomainMemberInfo(typeof(EnumModel), "IsExternal", EnumModel.IsExternalDomainPropertyId, typeof(EnumModel.IsExternalPropertyHandler)),
				new DomainMemberInfo(typeof(EnumModel), "IsFlags", EnumModel.IsFlagsDomainPropertyId, typeof(EnumModel.IsFlagsPropertyHandler)),
				new DomainMemberInfo(typeof(EnumModel), "GenerateCode", EnumModel.GenerateCodeDomainPropertyId, typeof(EnumModel.GenerateCodePropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "TargetEntityName", NavigationProperty.TargetEntityNameDomainPropertyId, typeof(NavigationProperty.TargetEntityNamePropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "IsCollection", NavigationProperty.IsCollectionDomainPropertyId, typeof(NavigationProperty.IsCollectionPropertyHandler)),
				new DomainMemberInfo(typeof(FilterPropertyModel), "IsOptional", FilterPropertyModel.IsOptionalDomainPropertyId, typeof(FilterPropertyModel.IsOptionalPropertyHandler)),
				new DomainMemberInfo(typeof(FilterPropertyModel), "IsInternal", FilterPropertyModel.IsInternalDomainPropertyId, typeof(FilterPropertyModel.IsInternalPropertyHandler)),
				new DomainMemberInfo(typeof(FilterPropertyModel), "InternalValue", FilterPropertyModel.InternalValueDomainPropertyId, typeof(FilterPropertyModel.InternalValuePropertyHandler)),
				new DomainMemberInfo(typeof(ReadMethodModel), "ItemId", ReadMethodModel.ItemIdDomainPropertyId, typeof(ReadMethodModel.ItemIdPropertyHandler)),
				new DomainMemberInfo(typeof(ReadMethodModel), "InclPaging", ReadMethodModel.InclPagingDomainPropertyId, typeof(ReadMethodModel.InclPagingPropertyHandler)),
				new DomainMemberInfo(typeof(ReadMethodModel), "UseQuery", ReadMethodModel.UseQueryDomainPropertyId, typeof(ReadMethodModel.UseQueryPropertyHandler)),
				new DomainMemberInfo(typeof(ReadMethodModel), "InclSorting", ReadMethodModel.InclSortingDomainPropertyId, typeof(ReadMethodModel.InclSortingPropertyHandler)),
				new DomainMemberInfo(typeof(ReadMethodModel), "DisplayOrder", ReadMethodModel.DisplayOrderDomainPropertyId, typeof(ReadMethodModel.DisplayOrderPropertyHandler)),
				new DomainMemberInfo(typeof(ReadMethodModel), "Attributes", ReadMethodModel.AttributesDomainPropertyId, typeof(ReadMethodModel.AttributesPropertyHandler)),
				new DomainMemberInfo(typeof(UpdatePropertyModel), "IsOptional", UpdatePropertyModel.IsOptionalDomainPropertyId, typeof(UpdatePropertyModel.IsOptionalPropertyHandler)),
				new DomainMemberInfo(typeof(UpdateMethodModel), "ItemId", UpdateMethodModel.ItemIdDomainPropertyId, typeof(UpdateMethodModel.ItemIdPropertyHandler)),
				new DomainMemberInfo(typeof(UpdateMethodModel), "UseDto", UpdateMethodModel.UseDtoDomainPropertyId, typeof(UpdateMethodModel.UseDtoPropertyHandler)),
				new DomainMemberInfo(typeof(UpdateMethodModel), "DisplayOrder", UpdateMethodModel.DisplayOrderDomainPropertyId, typeof(UpdateMethodModel.DisplayOrderPropertyHandler)),
				new DomainMemberInfo(typeof(ServiceModel), "Enabled", ServiceModel.EnabledDomainPropertyId, typeof(ServiceModel.EnabledPropertyHandler)),
				new DomainMemberInfo(typeof(ServiceModel), "InclCreate", ServiceModel.InclCreateDomainPropertyId, typeof(ServiceModel.InclCreatePropertyHandler)),
				new DomainMemberInfo(typeof(ServiceModel), "InclUpdate", ServiceModel.InclUpdateDomainPropertyId, typeof(ServiceModel.InclUpdatePropertyHandler)),
				new DomainMemberInfo(typeof(ServiceModel), "InclDelete", ServiceModel.InclDeleteDomainPropertyId, typeof(ServiceModel.InclDeletePropertyHandler)),
				new DomainMemberInfo(typeof(ServiceModel), "InclController", ServiceModel.InclControllerDomainPropertyId, typeof(ServiceModel.InclControllerPropertyHandler)),
				new DomainMemberInfo(typeof(ServiceModel), "Version", ServiceModel.VersionDomainPropertyId, typeof(ServiceModel.VersionPropertyHandler)),
				new DomainMemberInfo(typeof(ServiceModel), "ServiceUsings", ServiceModel.ServiceUsingsDomainPropertyId, typeof(ServiceModel.ServiceUsingsPropertyHandler)),
				new DomainMemberInfo(typeof(ServiceModel), "ServiceAttributes", ServiceModel.ServiceAttributesDomainPropertyId, typeof(ServiceModel.ServiceAttributesPropertyHandler)),
				new DomainMemberInfo(typeof(ServiceModel), "ControllerUsings", ServiceModel.ControllerUsingsDomainPropertyId, typeof(ServiceModel.ControllerUsingsPropertyHandler)),
				new DomainMemberInfo(typeof(ServiceModel), "ControllerAttributes", ServiceModel.ControllerAttributesDomainPropertyId, typeof(ServiceModel.ControllerAttributesPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "SourceMultiplicity", Association.SourceMultiplicityDomainPropertyId, typeof(Association.SourceMultiplicityPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "SourceRoleName", Association.SourceRoleNameDomainPropertyId, typeof(Association.SourceRoleNamePropertyHandler)),
				new DomainMemberInfo(typeof(Association), "GenSourceNavProperty", Association.GenSourceNavPropertyDomainPropertyId, typeof(Association.GenSourceNavPropertyPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "TargetMultiplicity", Association.TargetMultiplicityDomainPropertyId, typeof(Association.TargetMultiplicityPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "TargetRoleName", Association.TargetRoleNameDomainPropertyId, typeof(Association.TargetRoleNamePropertyHandler)),
				new DomainMemberInfo(typeof(Association), "GenTargetNavProperty", Association.GenTargetNavPropertyDomainPropertyId, typeof(Association.GenTargetNavPropertyPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "FkPropertyName", Association.FkPropertyNameDomainPropertyId, typeof(Association.FkPropertyNamePropertyHandler)),
				new DomainMemberInfo(typeof(Generalization), "Discriminator", Generalization.DiscriminatorDomainPropertyId, typeof(Generalization.DiscriminatorPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(Association), "Source", Association.SourceDomainRoleId),
				new DomainRolePlayerInfo(typeof(Association), "Target", Association.TargetDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClassHasProperties), "EntityModel", ClassHasProperties.EntityModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClassHasProperties), "Attribute", ClassHasProperties.AttributeDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelRootHasComments), "ModelRoot", ModelRootHasComments.ModelRootDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelRootHasComments), "Comment", ModelRootHasComments.CommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(Generalization), "Superclass", Generalization.SuperclassDomainRoleId),
				new DomainRolePlayerInfo(typeof(Generalization), "Subclass", Generalization.SubclassDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelRootHasTypes), "ModelRoot", ModelRootHasTypes.ModelRootDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelRootHasTypes), "Type", ModelRootHasTypes.TypeDomainRoleId),
				new DomainRolePlayerInfo(typeof(InterfaceHasOperation), "Interface", InterfaceHasOperation.InterfaceDomainRoleId),
				new DomainRolePlayerInfo(typeof(InterfaceHasOperation), "Operation", InterfaceHasOperation.OperationDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferencesSubjects), "Comment", CommentReferencesSubjects.CommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferencesSubjects), "Subject", CommentReferencesSubjects.SubjectDomainRoleId),
				new DomainRolePlayerInfo(typeof(Implementation), "Implement", Implementation.ImplementDomainRoleId),
				new DomainRolePlayerInfo(typeof(Implementation), "Implementor", Implementation.ImplementorDomainRoleId),
				new DomainRolePlayerInfo(typeof(EnumHasMembers), "EnumModel", EnumHasMembers.EnumModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(EnumHasMembers), "Member", EnumHasMembers.MemberDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClassHasNavigationProperties), "EntityModel", ClassHasNavigationProperties.EntityModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClassHasNavigationProperties), "NavigationProperty", ClassHasNavigationProperties.NavigationPropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(FilterPropertyModelHasProperty), "FilterPropertyModel", FilterPropertyModelHasProperty.FilterPropertyModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(FilterPropertyModelHasProperty), "PropertyModel", FilterPropertyModelHasProperty.PropertyModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ReadMethodModelHasFilterProperties), "ReadMethodModel", ReadMethodModelHasFilterProperties.ReadMethodModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ReadMethodModelHasFilterProperties), "FilterPropertyModel", ReadMethodModelHasFilterProperties.FilterPropertyModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(UpdatePropertyModelHasPropertyModel), "UpdatePropertyModel", UpdatePropertyModelHasPropertyModel.UpdatePropertyModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(UpdatePropertyModelHasPropertyModel), "PropertyModel", UpdatePropertyModelHasPropertyModel.PropertyModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(UpdateMethodModelHasUpdateProperties), "UpdateMethodModel", UpdateMethodModelHasUpdateProperties.UpdateMethodModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(UpdateMethodModelHasUpdateProperties), "UpdatePropertyModel", UpdateMethodModelHasUpdateProperties.UpdatePropertyModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ServiceModelHasReadMethodModels), "ServiceModel", ServiceModelHasReadMethodModels.ServiceModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ServiceModelHasReadMethodModels), "ReadMethodModel", ServiceModelHasReadMethodModels.ReadMethodModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ServiceModelHasUpdateMethods), "ServiceModel", ServiceModelHasUpdateMethods.ServiceModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ServiceModelHasUpdateMethods), "UpdateMethodModel", ServiceModelHasUpdateMethods.UpdateMethodModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityModelHasServiceModels), "EntityModel", EntityModelHasServiceModels.EntityModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityModelHasServiceModels), "ServiceModel", EntityModelHasServiceModels.ServiceModelDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(27);
				createElementMap.Add(typeof(ModelRoot), 0);
				createElementMap.Add(typeof(EntityModel), 1);
				createElementMap.Add(typeof(PropertyModel), 2);
				createElementMap.Add(typeof(Comment), 3);
				createElementMap.Add(typeof(ModelInterface), 4);
				createElementMap.Add(typeof(InterfaceOperation), 5);
				createElementMap.Add(typeof(EnumMember), 6);
				createElementMap.Add(typeof(EnumModel), 7);
				createElementMap.Add(typeof(NavigationProperty), 8);
				createElementMap.Add(typeof(FilterPropertyModel), 9);
				createElementMap.Add(typeof(ReadMethodModel), 10);
				createElementMap.Add(typeof(UpdatePropertyModel), 11);
				createElementMap.Add(typeof(UpdateMethodModel), 12);
				createElementMap.Add(typeof(ServiceModel), 13);
				createElementMap.Add(typeof(GenItDiagram), 14);
				createElementMap.Add(typeof(AssociationConnector), 15);
				createElementMap.Add(typeof(GeneralizationConnector), 16);
				createElementMap.Add(typeof(ImplementationConnector), 17);
				createElementMap.Add(typeof(CommentConnector), 18);
				createElementMap.Add(typeof(CommentBoxShape), 19);
				createElementMap.Add(typeof(ClassShape), 20);
				createElementMap.Add(typeof(InterfaceShape), 21);
				createElementMap.Add(typeof(EnumShape), 22);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Dyvenix.GenIt.GenItDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new ModelRoot(partition, propertyAssignments);
				case 1: return new EntityModel(partition, propertyAssignments);
				case 2: return new PropertyModel(partition, propertyAssignments);
				case 3: return new Comment(partition, propertyAssignments);
				case 4: return new ModelInterface(partition, propertyAssignments);
				case 5: return new InterfaceOperation(partition, propertyAssignments);
				case 6: return new EnumMember(partition, propertyAssignments);
				case 7: return new EnumModel(partition, propertyAssignments);
				case 8: return new NavigationProperty(partition, propertyAssignments);
				case 9: return new FilterPropertyModel(partition, propertyAssignments);
				case 10: return new ReadMethodModel(partition, propertyAssignments);
				case 11: return new UpdatePropertyModel(partition, propertyAssignments);
				case 12: return new UpdateMethodModel(partition, propertyAssignments);
				case 13: return new ServiceModel(partition, propertyAssignments);
				case 14: return new GenItDiagram(partition, propertyAssignments);
				case 15: return new AssociationConnector(partition, propertyAssignments);
				case 16: return new GeneralizationConnector(partition, propertyAssignments);
				case 17: return new ImplementationConnector(partition, propertyAssignments);
				case 18: return new CommentConnector(partition, propertyAssignments);
				case 19: return new CommentBoxShape(partition, propertyAssignments);
				case 20: return new ClassShape(partition, propertyAssignments);
				case 21: return new InterfaceShape(partition, propertyAssignments);
				case 22: return new EnumShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(17);
				createElementLinkMap.Add(typeof(Association), 0);
				createElementLinkMap.Add(typeof(ClassHasProperties), 1);
				createElementLinkMap.Add(typeof(ModelRootHasComments), 2);
				createElementLinkMap.Add(typeof(Generalization), 3);
				createElementLinkMap.Add(typeof(ModelRootHasTypes), 4);
				createElementLinkMap.Add(typeof(InterfaceHasOperation), 5);
				createElementLinkMap.Add(typeof(CommentReferencesSubjects), 6);
				createElementLinkMap.Add(typeof(Implementation), 7);
				createElementLinkMap.Add(typeof(EnumHasMembers), 8);
				createElementLinkMap.Add(typeof(ClassHasNavigationProperties), 9);
				createElementLinkMap.Add(typeof(FilterPropertyModelHasProperty), 10);
				createElementLinkMap.Add(typeof(ReadMethodModelHasFilterProperties), 11);
				createElementLinkMap.Add(typeof(UpdatePropertyModelHasPropertyModel), 12);
				createElementLinkMap.Add(typeof(UpdateMethodModelHasUpdateProperties), 13);
				createElementLinkMap.Add(typeof(ServiceModelHasReadMethodModels), 14);
				createElementLinkMap.Add(typeof(ServiceModelHasUpdateMethods), 15);
				createElementLinkMap.Add(typeof(EntityModelHasServiceModels), 16);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Dyvenix.GenIt.GenItDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new Association(partition, roleAssignments, propertyAssignments);
				case 1: return new ClassHasProperties(partition, roleAssignments, propertyAssignments);
				case 2: return new ModelRootHasComments(partition, roleAssignments, propertyAssignments);
				case 3: return new Generalization(partition, roleAssignments, propertyAssignments);
				case 4: return new ModelRootHasTypes(partition, roleAssignments, propertyAssignments);
				case 5: return new InterfaceHasOperation(partition, roleAssignments, propertyAssignments);
				case 6: return new CommentReferencesSubjects(partition, roleAssignments, propertyAssignments);
				case 7: return new Implementation(partition, roleAssignments, propertyAssignments);
				case 8: return new EnumHasMembers(partition, roleAssignments, propertyAssignments);
				case 9: return new ClassHasNavigationProperties(partition, roleAssignments, propertyAssignments);
				case 10: return new FilterPropertyModelHasProperty(partition, roleAssignments, propertyAssignments);
				case 11: return new ReadMethodModelHasFilterProperties(partition, roleAssignments, propertyAssignments);
				case 12: return new UpdatePropertyModelHasPropertyModel(partition, roleAssignments, propertyAssignments);
				case 13: return new UpdateMethodModelHasUpdateProperties(partition, roleAssignments, propertyAssignments);
				case 14: return new ServiceModelHasReadMethodModels(partition, roleAssignments, propertyAssignments);
				case 15: return new ServiceModelHasUpdateMethods(partition, roleAssignments, propertyAssignments);
				case 16: return new EntityModelHasServiceModels(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "Dyvenix.GenIt.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GenItDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (GenItDomainModel.resourceManager == null)
				{
					GenItDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(GenItDomainModel).Assembly);
				}
				return GenItDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return GenItDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return GenItDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (GenItDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new GenItCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					GenItDomainModel.copyClosure = copyFilter;
				}
				return GenItDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (GenItDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new GenItDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					GenItDomainModel.removeClosure = removeFilter;
				}
				return GenItDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::Dyvenix.GenIt.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::Dyvenix.GenIt.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::Dyvenix.GenIt.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::Dyvenix.GenIt.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::Dyvenix.GenIt.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::Dyvenix.GenIt.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::Dyvenix.GenIt.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::Dyvenix.GenIt.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::Dyvenix.GenIt.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::Dyvenix.GenIt.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::Dyvenix.GenIt.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::Dyvenix.GenIt.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::Dyvenix.GenIt.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::Dyvenix.GenIt.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class GenItDeleteClosure : GenItDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public GenItDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class GenItDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public GenItDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::Dyvenix.GenIt.ClassHasProperties.AttributeDomainRoleId, true);
			DomainRoles.Add(global::Dyvenix.GenIt.ModelRootHasComments.CommentDomainRoleId, true);
			DomainRoles.Add(global::Dyvenix.GenIt.ModelRootHasTypes.TypeDomainRoleId, true);
			DomainRoles.Add(global::Dyvenix.GenIt.InterfaceHasOperation.OperationDomainRoleId, true);
			DomainRoles.Add(global::Dyvenix.GenIt.EnumHasMembers.MemberDomainRoleId, true);
			DomainRoles.Add(global::Dyvenix.GenIt.ClassHasNavigationProperties.NavigationPropertyDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class GenItCopyClosure : GenItCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public GenItCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class GenItCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public GenItCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace Dyvenix.GenIt
{
	/// <summary>
	/// DomainEnumeration: AccessModifier
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum AccessModifier
	{
	}
}
namespace Dyvenix.GenIt
{
	/// <summary>
	/// DomainEnumeration: TypeAccessModifier
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TypeAccessModifier
	{
	}
}
namespace Dyvenix.GenIt
{
	/// <summary>
	/// DomainEnumeration: InheritanceModifier
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum InheritanceModifier
	{
	}
}
namespace Dyvenix.GenIt
{
	/// <summary>
	/// DomainEnumeration: Multiplicity
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Multiplicity
	{
		/// <summary>
		/// ZeroOne
		/// Zero or one
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.Multiplicity/ZeroOne.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		ZeroOne = 0,
		/// <summary>
		/// One
		/// Exactly one
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.Multiplicity/One.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		One = 1,
		/// <summary>
		/// Many
		/// Zero or more
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.Multiplicity/Many.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Many = 2,
	}
}
namespace Dyvenix.GenIt
{
	/// <summary>
	/// DomainEnumeration: OperationConcurrency
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum OperationConcurrency
	{
		/// <summary>
		/// Sequential
		/// Sequential execution
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.OperationConcurrency/Sequential.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Sequential = 0,
		/// <summary>
		/// Guarded
		/// Guarded execution
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.OperationConcurrency/Guarded.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Guarded = 1,
		/// <summary>
		/// Concurrent
		/// Concurrent execution
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.OperationConcurrency/Concurrent.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Concurrent = 2,
	}
}
namespace Dyvenix.GenIt
{
	/// <summary>
	/// DomainEnumeration: DataType
	/// Common C# data types
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum DataType
	{
		/// <summary>
		/// String
		/// System.String
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/String.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		String = 0,
		/// <summary>
		/// Int32
		/// System.Int32
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Int32.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Int32 = 5,
		/// <summary>
		/// Boolean
		/// System.Boolean
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Boolean.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Boolean = 1,
		/// <summary>
		/// Guid
		/// System.Guid
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Guid.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Guid = 17,
		/// <summary>
		/// DateTime
		/// System.DateTime
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/DateTime.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		DateTime = 14,
		/// <summary>
		/// Byte
		/// System.Byte
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Byte.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Byte = 2,
		/// <summary>
		/// SByte
		/// System.SByte
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/SByte.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		SByte = 3,
		/// <summary>
		/// Int16
		/// System.Int16
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Int16.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Int16 = 4,
		/// <summary>
		/// Int64
		/// System.Int64
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Int64.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Int64 = 6,
		/// <summary>
		/// UInt16
		/// System.UInt16
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/UInt16.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		UInt16 = 7,
		/// <summary>
		/// UInt32
		/// System.UInt32
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/UInt32.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		UInt32 = 8,
		/// <summary>
		/// UInt64
		/// System.UInt64
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/UInt64.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		UInt64 = 9,
		/// <summary>
		/// Single
		/// System.Single
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Single.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Single = 10,
		/// <summary>
		/// Double
		/// System.Double
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Double.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Double = 11,
		/// <summary>
		/// Decimal
		/// System.Decimal
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Decimal.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Decimal = 12,
		/// <summary>
		/// Char
		/// System.Char
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Char.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Char = 13,
		/// <summary>
		/// DateTimeOffset
		/// System.DateTimeOffset
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/DateTimeOffset.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		DateTimeOffset = 15,
		/// <summary>
		/// TimeSpan
		/// System.TimeSpan
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/TimeSpan.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		TimeSpan = 16,
		/// <summary>
		/// ByteArray
		/// Byte array (byte[])
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/ByteArray.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		ByteArray = 18,
		/// <summary>
		/// Object
		/// System.Object
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Object.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Object = 19,
		/// <summary>
		/// Enum
		/// Enum type - see EnumTypeName property
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/Enum.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		Enum = 20,
		/// <summary>
		/// StringList
		/// List of strings (List<string>)
		/// </summary>
		[DslDesign::DescriptionResource("Dyvenix.GenIt.DataType/StringList.Description", typeof(global::Dyvenix.GenIt.GenItDomainModel), "Dyvenix.GenIt.GeneratedCode.DomainModelResx")]
		StringList = 21,
	}
}

