//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyvenix.GenIt
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "gmdl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"GenIt";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Dyvenix";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID GenItDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GenItCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID GenItExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GenItCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewGenItExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GenItCommandSetId), 0x0001);
	
		// Package identifier
		public const string GenItPackageId = "3aa8cbb2-f0c4-4628-bc99-158569733469";
		
		// Editor factory identifier
		public const string GenItEditorFactoryId = "185dd91f-393a-4f15-8ba0-9406fa4ffc9b";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string GenItModelExplorerToolWindowId = "584bbce2-fa64-47c0-a8a5-f0500f850804";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Dyvenix.GenIt
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string GenItCommandSetId = "94fe6316-0e08-4ace-9bb9-f1c3774d3a14";
	}
}